[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# optimizer = true
# optimizer_runs = 200 (uncomment for deployment to reduce execution and deployment costs)



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[dependencies]
openzeppelin-contracts = "5.0.2"

[profile.sepolia]
rpc_url = "${SEPOLIA_RPC_URL}"

[profile.env]
PRIVATE_KEY = "PRIVATE_KEY"
